# Generated by Django 2.2.5 on 2021-12-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verified',
            new_name='email_confirmed',
        ),
    ]
