# Generated by Django 2.2.5 on 2021-12-12 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211212_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_confirmed',
            new_name='eamil_verified',
        ),
    ]
