# Generated by Django 2.2.5 on 2021-12-09 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20211209_0911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facilitiy',
            new_name='Facility',
        ),
    ]
